# -*- coding: utf-8 -*-
"""task_list.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bO63KkZKQeTpJGvOzm8UEAOjUbKL6I3H
"""

import json
import os

FILE_NAME = "tasks.json"


def load_tasks():
    if not os.path.exists(FILE_NAME):
        return []
    try:
        with open(FILE_NAME, "r", encoding="utf-8") as file:
            return json.load(file)
    except (json.JSONDecodeError, IOError):
        return []


def save_tasks(tasks):
    with open(FILE_NAME, "w", encoding="utf-8") as file:
        json.dump(tasks, file, indent=4)


def add_task(tasks):
    title = input("Enter task: ").strip()
    if title == "":
        print("Task title cannot be empty.")
        return
    tasks.append({"title": title, "done": False})
    save_tasks(tasks)
    print("Task added.")


def list_tasks(tasks):
    if not tasks:
        print("No tasks found.")
        return
    for index, task in enumerate(tasks, start=1):
        status = "Done" if task["done"] else " "
        print(f"{index}. [{status}] {task['title']}")


def mark_task_done(tasks):
    if not tasks:
        print("No tasks to mark.")
        return
    list_tasks(tasks)
    try:
        number = int(input("Enter task number to mark as done: "))
        if number < 1 or number > len(tasks):
            print("Invalid task number.")
            return
        tasks[number - 1]["done"] = True
        save_tasks(tasks)
        print("Task marked as done.")
    except ValueError:
        print("Invalid input. Please enter a number.")


def main():
    tasks = load_tasks()
    while True:
        print("\n1. Add Task")
        print("2. View Tasks")
        print("3. Mark Task as Done")
        print("4. Exit")
        choice = input("Choose an option: ").strip()

        if choice == "1":
            add_task(tasks)
        elif choice == "2":
            list_tasks(tasks)
        elif choice == "3":
            mark_task_done(tasks)
        elif choice == "4":
            break
        else:
            print("Invalid choice.")


if __name__ == "__main__":
    main()

"""# Nouvelle section"""

